language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  
before_script:
  - phpenv config-rm xdebug.ini
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - phpenv rehash

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src"

notifications:
  email: false
