sudo: required

language: php

services:
  - docker

before_script:
  - docker-compose up

script:
  - docker-compose exec tests vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src
  - docker-compose exec tests vendor/bin/codecept run

notifications:
  email: false
