sudo: required

language: generic

services:
  - docker

before_script:
  - docker-compose up

script:
  - docker-compose -f docker-compose.tests.yml exec tests vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src
  - docker-compose -f docker-compose.tests.yml exec tests vendor/bin/codecept run

notifications:
  email: false
