sudo: required

language: generic

services:
  - docker

before_script:
  - docker-compose -f docker-compose.tests.yml up -d
  - echo -n "Waiting for end of composer dependencies installation ...";while :;do [[ -f "vendor/autoload.php" ]] && break;echo -n ".";sleep 1;done
  - docker-compose -f docker-compose.tests.yml exec db echo "CREATE DATABASE opencomp_test CHARACTER SET utf8 COLLATE utf8_general_ci" | mysql -h 127.0.0.1 -u root -proot
  - docker-compose -f docker-compose.tests.yml exec tests sh -c "vendor/bin/codecept build"

script:
  - docker-compose -f docker-compose.tests.yml exec tests sh -c "php vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src"
  - echo -n "Waiting for nginx to start ...";while :;do [[ test $(docker-compose -f docker-compose.tests.yml exec tests $(wc -l /var/run/nginx.pid | cut -d' ' -f1) == "0" ]] && break;echo -n ".";sleep 1;done
  - docker-compose -f docker-compose.tests.yml exec tests sh -c "php vendor/bin/codecept run"

notifications:
  email: false
