language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sh -c "mysql -e 'CREATE DATABASE opencomp_test;'"
  - chmod -R 777 tmp
  - echo "<?php class DATABASE_CONFIG { public \$test = array('datasource' => 'Database/Mysql', 'database' => 'opencomp_test', 'host' => '0.0.0.0', 'login' => 'travis', 'persistent' => false); }" > Config/database.php
  - composer install --dev

script:
  - Console/cake test AllTests --stderr

notifications:
  email: false