version: '2'

services:
  web:
    image: opencomp/web:latest
    #build: ../Dockerfiles/web
    ports:
      - "80:80"
    depends_on:
      - db
      - message_queue 
    volumes:
      - ./:/var/www/html
  java_servlets:
    image: tomcat:7-jre8
    volumes:
      - ./java_servlets:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
  message_queue:
    image: schickling/beanstalkd:latest
  pdf_worker:
    image: opencomp/pdf_worker:latest
    #build: ../Dockerfiles/pdf_worker
    depends_on:
      - message_queue
      - db
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
        - data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  data:
