version: '2'

services:
  web:
    #image: opencomp/web:latest
    build: ../opencomp_docker/web
    environment:
      DATABASE_URL: mysql://root:root@db/opencomp
    ports:
      - "80:8080"
    depends_on:
      - db
      - message_queue
      - postfix
    volumes:
      - ./:/var/www/html
      - ./var/lib/mysql-files:/var/www/html/tmp/mysql-files
  tests:
    image: opencomp/web:latest
    environment:
      # We override standard database for acceptance testing purpose
      DATABASE_URL: mysql://root:root@db/opencomp_test
    ports:
      - "7357:8080"
    depends_on:
      - db
      - message_queue
      - postfix
    volumes:
      - ./:/var/www/html
  postfix:
    image: elsdoerfer/exim-sender
    environment:
      ALLOWED_HOSTS: 172.18.0.0/24
  java_servlets:
    image: tomcat:7-jre8
    volumes:
      - ./java_servlets:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
      - "25:25"
  message_queue:
    image: schickling/beanstalkd:latest
  pdf_worker:
    image: opencomp/pdf_worker:latest
    #build: ../Dockerfiles/pdf_worker
    depends_on:
      - message_queue
      - db
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
        - data:/var/lib/mysql
        - ./var/lib/mysql-files:/var/lib/mysql-files
    ports:
      - "3306:3306"
  memcached:
      image: memcached:alpine
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: myadmin
      environment:
       - PMA_HOST=db
       - PMA_USER=root
       - PMA_PASSWORD=root
      restart: always
      ports:
       - 8000:80
      volumes:
       - /sessions

volumes:
  data:
