version: '2'

services:
  tests:
    image: opencomp/web:latest
    environment:
      # We override standard database for acceptance testing purpose
      DATABASE_URL: mysql://root:root@db/opencomp_test
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
