version: '2'

services:
  tests:
    image: opencomp/web:latest
    environment:
      # We override standard database for acceptance testing purpose
      DATABASE_URL: mysql://root:root@db/opencomp_test
    ports:
      - "8080:8080"
    depends_on:
      - db
      - memcached
    volumes:
      - ./:/var/www/html
  memcached:
    image: memcached:alpine
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
